version: "3.3"
services:
  saturn-node:
    image: ghcr.io/filecoin-saturn/l1-node:${SATURN_NETWORK:-main}
    container_name: saturn-node
    restart: unless-stopped
    environment:
      SATURN_NETWORK: "${SATURN_NETWORK:main}"
      FIL_WALLET_ADDRESS: "${FIL_WALLET_ADDRESS:f1dul2ufwqjbu4bzgxla6mshjoxiizd2bwydi2pcq}"
      NODE_OPERATOR_EMAIL: "${NODE_OPERATOR_EMAIL:bol7458@gmail.com}"
      SPEEDTEST_SERVER_CONFIG: "${SPEEDTEST_SERVER_CONFIG}"
    ulimits:
        nofile:
          soft: 1000000
          hard: 1000000
    ports:
      - 80:80
      - 443:443
    network_mode: host
    stop_signal: SIGTERM
    stop_grace_period: 30m
    labels:
      com.centurylinklabs.watchtower.scope: saturn
      com.centurylinklabs.watchtower.enable: "true"
      com.centurylinklabs.watchtower.lifecycle.pre-update-timeout: 30
      com.centurylinklabs.watchtower.lifecycle.post-update-timeout: 30
    volumes:
      - ${SATURN_HOME:-$HOME}/shared:/usr/src/app/shared

  watchtower:
      image: containrrr/watchtower
      container_name: saturn-watchtower
      restart: always
      environment:
        WATCHTOWER_POLL_INTERVAL: 3600
        WATCHTOWER_LABEL_ENABLE: "true"
        WATCHTOWER_SCOPE: saturn
      labels:
        com.centurylinklabs.watchtower.scope: saturn
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

